spring.application.name=avito
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9080/realms/avitorealm

jwt.auth.converter.resource-id=avitofrontend
jwt.auth.converter.principal-attribute=preferred_username

logging.level.org.springframework.security=DEBUG
spring.datasource.url=jdbc:postgresql://localhost:14092/keycloak
spring.datasource.username=keycloak
spring.datasource.password=keycloak
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.oauth.client-id=avitofrontend
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth2-redirect-url=http://localhost:8081/swagger-ui
server.port=8081
