
server.port=8081


spring.application.name=avito-backend

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:14082/realms/avitorealm

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.oauth.client-id=avitofrontend
springdoc.swagger-ui.oauth.app-name=Avito Backend API
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true


logging.level.org.springframework.security=TRACE