spring:
  datasource:
    url: jdbc:postgresql://postgres:5433/avito_chat_db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/avitorealm

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/